angular.module('app')
	.controller('refundController',['$scope',function($scope){
		$scope.data = [
			{
				img:'./images/home_Salability_Series-img_2@3x.png',
				state:'退款成功',
				title:'日本sana豆乳洗面奶女深层清洁补水保湿控油泡沫洁面',
				para:'化妆品净含量:150g/ml',
				price:'￥69.00'
			},
			{
				img:'./images/home_Salability_Series-img_1@3x.png',
				state:'退款成功',
				title:'日本sana豆乳洗面奶女深层清洁补水保湿控油泡沫洁面',
				para:'化妆品净含量:4片',
				price:'￥65.00'
			},
			{
				img:'./images/home_Salability_Series-img_3@3x.png',
				state:'退款成功',
				title:'日本sana豆乳洗面奶女深层清洁补水保湿控油泡沫洁面',
				para:'化妆品净含量:150g/ml',
				price:'￥56.00'
			},
			{
				img:'./images/home_Salability_Series-img_1@3x.png',
				state:'退款成功',
				title:'日本sana豆乳洗面奶女深层清洁补水保湿控油泡沫洁面',
				para:'化妆品净含量:150g/ml',
				price:'￥85.00'
			},
			{
				img:'./images/home_Salability_Series-img_3@3x.png',
				state:'退款成功',
				title:'日本sana豆乳洗面奶女深层清洁补水保湿控油泡沫洁面',
				para:'化妆品净含量:150g/ml',
				price:'￥56.00'
			},
		]
	}])
